server:
  port: ${PAYMENT_SERVICE_PORT:8085}

spring:
  application:
    name: payment-service

  datasource:
    url: ${PAYMENT_DB_URL:jdbc:mysql://localhost:3307/flashticket_payment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kuala_Lumpur}
    username: ${PAYMENT_DB_USERNAME:root}
    password: ${PAYMENT_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true
    baseline-on-migrate: true
    baseline-version: "0"
    table: flyway_payment_schema_history

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      retries: 10
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        spring.json.add.type.headers: true

    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: com.flashticket.paymentservice.event
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.flashticket.paymentservice.event.OrderCreatedEvent

    listener:
      ack-mode: record

order-service:
  base-url: ${ORDER_SERVICE_BASE_URL:http://localhost:8084}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

logging:
  level:
    root: WARN
    com.flashticket.paymentservice: INFO

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
