server:
  port: 8082

spring:
  application:
    name: tikcet-service

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3307/flashticket_auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kuala_Lumpur
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

mybatis:
  mapper-locations: classpath:mapper/*.xml

  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.flashticket.ticketservice.mapper: DEBUG


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
